version: '3.8'

services:
  test-worker:
    image: radusimonica/test_distributor:latest
    command: java -jar /test-distributor/distributedTest.jar --worker --rabbitHost rabbitmq --requestQueue q.request.test --responseQueue q.receive.result
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    deploy:
      replicas: 4
      restart_policy:
        condition: none
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: overlay
    external: true
    attachable: true

secrets:
  rabbitmq-pass:
    external: true